// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf2V1otWewIuhVSzfHYRHZSZIfkpDWabw',
    appId: '1:320596142744:android:57dbe8bfcf178365d13eed',
    messagingSenderId: '320596142744',
    projectId: 'chat-b254f',
    databaseURL:
        'https://chat-b254f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-b254f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqlvCXQJN67cem5oxMjd3CZOS8UJraFLc',
    appId: '1:320596142744:ios:9d7f2b26967dd8f1d13eed',
    messagingSenderId: '320596142744',
    projectId: 'chat-b254f',
    databaseURL:
        'https://chat-b254f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-b254f.firebasestorage.app',
    iosBundleId: 'com.example.communityapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqlvCXQJN67cem5oxMjd3CZOS8UJraFLc',
    appId: '1:320596142744:ios:9d7f2b26967dd8f1d13eed',
    messagingSenderId: '320596142744',
    projectId: 'chat-b254f',
    databaseURL:
        'https://chat-b254f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-b254f.firebasestorage.app',
    iosBundleId: 'com.example.communityapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvCFBgAiok4AiVNTGpgPi6wL0csRCyl7Q',
    appId: '1:320596142744:web:0abb274b04b3eb7fd13eed',
    messagingSenderId: '320596142744',
    projectId: 'chat-b254f',
    authDomain: 'chat-b254f.firebaseapp.com',
    databaseURL:
        'https://chat-b254f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-b254f.firebasestorage.app',
    measurementId: 'G-ZNQ41X5441',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBoQGCn3G0-BHhM0CEWErdkEYX59hqKxEU",
      authDomain: "chat-b254f.firebaseapp.com",
      databaseURL:
          "https://chat-b254f-default-rtdb.asia-southeast1.firebasedatabase.app",
      projectId: "chat-b254f",
      storageBucket: "chat-b254f.firebasestorage.app",
      messagingSenderId: "320596142744",
      appId: "1:320596142744:web:265411438b165d2cd13eed",
      measurementId: "G-LYN04E9H2V");
}
